import { Dimensions, StyleSheet } from 'react-native'

export default StyleSheet.create({
  parent: {
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height,
    backgroundColor: '#181818',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  topBar:{
    width: '100%',
    height: '10%',
    borderWidth: 0,
    borderColor: '#fff',
    justifyContent:'space-between',
    display: 'flex',
    flexDirection: 'row',
    position:'absolute',
    top: 0,
  },
  leftBar:{
    width: '35%',
    height: '50%',
    justifyContent:'center',
    alignSelf: 'center',
    borderWidth: 0,
    borderColor: '#fff',
    marginStart: '2%',
  },
  date:{
    color: '#C0C0C0',
    fontSize: 12,
  },
  title:{
    color:'#fff',
    fontSize: 18,
  },
  btnProfile:{
    width: '10%',
    height: '50%',
    borderWidth: 0,
    borderColor: '#fff',
    marginStart: '3%',
    alignSelf: 'center',
  },
  imgProfile:{
    width: '100%',
    height: '100%',
    alignSelf:'center',
    marginEnd: 20,
  },
  calenderView:{
    width: '95%',
    height: '18%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf:'center',
    position:'absolute',
    top: '12%',
  },
  currMeetings:{
    width: '95%',
    height: '20%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf:'center',
    marginTop: '70%',
  },
  meetingTitle:{
    color: '#F5F5F5FD',
    fontSize: 19,
    fontWeight: '700'
  },
  meetings:{
    width: '95%',
    flex: 1,
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf:'center',
    display:'flex',
    flexDirection: 'row',
    justifyContent:'center',
    backgroundColor:'#2B2B2B',
    marginTop: 5,
    borderRadius: 15,
  },
  sched_meet:{
    width: '30%',
    height: '90%',
    borderWidth: 0,
    borderColor: '#fff',
    justifyContent:'center',
  },
  cap:{
    fontSize: 15,
    color :'#C0C0C0',
    alignSelf:'center',
  },
  top:{
    fontSize: 28,
    color :'#fff',
    alignSelf:'center',
  },
  imgIcon:{
    width: 25,
    height: 25,
    alignSelf:'center',
  },
  myMeetings:{
    width: '95%',
    height: '30%',
    position: 'absolute',
    bottom: '8%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf:'center',
  },
  myMeetingsTitle:{
    color: '#F5F5F5FD',
    fontSize: 19,
    fontWeight: '700'
  },
  meeting:{
    width: '95%',
    flex:1,
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf:'center',
    marginTop: 10,
    backgroundColor:'#2B2B2B',
    borderRadius:15,
  },
  scroller:{
    width: '95%',
    flex:1,
    zIndex: 1001,
    position:'absolute',
    display:'flex',
    flexDirection:'column',
  },
  block:{
    width: '90%',
    height: 45,
    borderWidth: 0,
    borderColor: '#fff',
    justifyContent:'center',
    display:'flex',
    flexDirection:'row',
    marginTop: 15,
    alignSelf:'center',
  },
  sep:{
    width: '98%',
    borderWidth: 1,
    borderColor: '#fff',
    alignSelf:'center',
  },
  mtBlock:{
    width: '90%',
    height: '100%',
    borderWidth: 0,
    borderColor: '#fff',
    marginStart: '1%',
    display:'flex',
    flexDirection:'row',
    borderRadius:15,
    position:'absolute',
    zIndex: 1001,
    alignSelf:'center',
  },
  mtOdd:{
    backgroundColor:'#4169e1'
  },
  mtEven:{
    backgroundColor:'#ffa6c9',
  },
  mtCap:{
    alignSelf:'center',
    color: '#F5F5F5FD',
    fontSize: 18,
    marginStart: '5%',
  },
  mtEvenCap:{
    color:'#111',
  }
})