import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  parent: {
    flex: 1,
    backgroundColor: '#F5F5F5FD',
    borderWidth: 0,
    borderColor: '#111',
  },
  topBar: {
    width: '100%',
    height: '7%',
    borderWidth: 0,
    borderColor: '#111',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  menu: {
    alignSelf: 'center',
    marginEnd: '2%',
  },
  dashTitle: {
    alignSelf: 'center',
    marginStart: '2%',
    fontSize: 18,
    color: '#111',
    fontFamily: 'Open-Sans',
  },
  nextSchedule: {
    width: '100%',
    height: '35%',
    borderWidth: 0,
    borderColor: '#111',
    alignSelf: 'center',
    marginTop: '10%',
  },
  titleBar: {
    width: '100%',
    height: '18%',
    borderWidth: 0,
    borderColor: '#111',
  },
  next: {
    fontSize: 22,
    color: '#111',
    fontWeight: '600',
    marginStart: '5%',
    fontFamily: 'Open-Sans',
  },
  nextCard: {
    width: '90%',
    flex: 1,
    height: '90%',
    marginBottom: '2%',
    borderWidth: 0,
    borderColor: '#111',
    alignSelf: 'center',
    backgroundColor: '#6495ed',
    borderRadius: 15,
    elevation: 5,
  },
  colOne: {
    width: '100%',
    borderWidth: 0,
    borderColor: '#111',
    height: '75%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  colLeft: {
    width: '20%',
    height: '100%',
    borderWidth: 0,
    borderColor: '#111',
    borderTopLeftRadius: 15,
    justifyContent: 'center',
  },
  ColRight: {
    width: '80%',
    height: '100%',
    borderWidth: 0,
    borderColor: '#111',
    borderTopRightRadius: 15,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  icon: {
    width: 60,
    height: 60,
    alignSelf: 'center',
    position: 'absolute',
    top: '15%',
  },
  date: {
    fontSize: 26,
    color: '#fff',
    marginStart: '5%',
    fontFamily: 'Open-Sans',
  },
  schedTime: {
    fontSize: 18,
    color: '#C0C0C0',
    marginStart: '5%',
    fontFamily: 'Open-Sans',
  },
  team: {
    width: '100%',
    height: 35,
    borderWidth: 0,
    borderColor: '#111',
    display: 'flex',
    flexDirection: 'row',
    marginTop: 2,
  },
  yin: {
    width: 25,
    height: 25,
    marginStart: '3%',
    alignSelf: 'center',
  },
  teamName: {
    color: '#fff',
    alignSelf: 'center',
    fontSize: 18,
    marginStart: '3%',
    fontFamily: 'Open-Sans',
  },
  venue: {
    color: '#fff',
    alignSelf: 'center',
    fontSize: 18,
    marginStart: '3%',
    fontFamily: 'Open-Sans',
  },
  today: {
    width: '95%',
    flex: 1,
    borderWidth: 0,
    borderColor: '#111',
    alignSelf: 'center',
    marginBottom: '1%',
    marginTop: '5%',
  },
  todayTitle: {
    color: '#111',
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Open-Sans',
    marginStart: '3%',
  },
  scrollView: {
    flex: 1,
    borderWidth: 0,
    borderColor: '#111',
    marginTop: '2%',
  },
  scroll: {
    width: '100%',
    flex: 1,
    position: 'absolute',
    zIndex: 1001,
  },
  card: {
    width: '95%',
    height: 95,
    marginTop: 15,
    alignSelf: 'center',
    elevation: 4,
  },
  sub: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    marginTop: '5%',
  },
  cardTitle: {
    marginStart: '3%',
  },
  heading: {
    marginStart: '3%',
    fontFamily: 'Open-Sans',
    fontSize: 16,
  },
  cardTime: {
    alignSelf: 'center',
    marginStart: '5%',
  },
})
