import { Dimensions, StyleSheet } from 'react-native'

export default StyleSheet.create({
  parent: {
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height,
    backgroundColor: '#181818',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  topBar: {
    width: '90%',
    height: '10%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '10%',
  },
  logo:{
    alignSelf:'center',
  },
  title: {
    fontSize: 26,
    color: '#fff',
    alignSelf: 'center',
    marginTop: 10,
  },
  err:{
    width: '90%',
    height: '5%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  error:{
    color: '#FF0038',
    fontSize: 18,
    alignSelf: 'center',
  },
  container: {
    width: '90%',
    height: '40%',
    borderWidth: 0,
    borderColor: '#fff',
    alignSelf: 'center',
  },
  txtInput: {
    width: '85%',
    fontSize: 16,
    borderBottomWidth: 1,
    borderColor: '#fff',
    alignSelf: 'center',
    color: '#fff',
    marginTop: 15,
  },
  lblForgotPassword: {
    fontSize: 14,
    color: '#fff',
    alignSelf: 'flex-end',
    marginTop: 10,
    marginEnd: 25,
  },
  btnLogin: {
    width: '55%',
    height: '20%',
    alignSelf: 'center',
    marginTop: 25,
    borderRadius: 25,
  },
  linearGradient:{
    width: '100%',
    height: '100%',
    borderRadius: 30,
    justifyContent: 'center',
  },
  btnCap: {
    fontSize: 26,
    color: '#fff',
    alignSelf: 'center',
    fontWeight:'700',
  },
  no_acc:{
    width: '85%',
    height: '5%',
    alignSelf: 'center',
    position: 'absolute',
    bottom: '5%',
    display: 'flex',
    flexDirection:'row',
    justifyContent:'center',
  },
  acc_cap:{
    fontSize: 16,
    color: '#fff',
  },
  link:{
    marginLeft: 5,
    fontWeight:'700',
  }
})
