import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  parent: {
    flex: 1,
    backgroundColor: '#F5F5F5FD',
    justifyContent: 'center',
  },
  topBar: {
    width: '100%',
    height: '5%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 0,
    borderColor: '#111',
  },
  menu: {
    alignSelf: 'center',
    marginEnd: '2%',
  },
  Title: {
    alignSelf: 'center',
    marginStart: '2%',
    fontSize: 24,
    color: '#111',
    fontFamily: 'Open-Sans',
  },
  content: {
    flex: 1,
    backgroundColor: '#F5F5F5FD',
    marginTop: 15,
  },
  block: {
    width: '95%',
    height: '11%',
    marginTop: 20,
    alignSelf: 'center',
  },
  blockTitle: {
    marginStart: '13%',
    fontSize: 16,
  },
  input: {
    width: '85%',
    flex: 1,
    borderWidth: 0,
    borderColor: '#111',
    alignSelf: 'center',
    marginTop: 5,
    borderRadius: 25,
    paddingStart: 15,
    fontSize: 18,
    backgroundColor: '#fff',
    fontFamily: 'Open-Sans',
  },
  inputBlock: {
    width: '85%',
    borderRadius: 25,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  Dateinput: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 25,
    paddingStart: 45,
    fontSize: 18,
    marginTop: 5,
    fontFamily: 'Open-Sans',
  },
  imgDate: {
    width: 22,
    height: 22,
    position: 'absolute',
    left: 15,
    zIndex: 101,
  },
  outerBlock: {
    width: '95%',
    height: '11%',
    borderWidth: 0,
    borderColor: '#111',
    marginTop: 20,
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  left: {
    width: '45%',
  },
  right: {
    width: '45%',
  },
  startTime: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 25,
    paddingStart: 45,
    fontSize: 18,
    marginTop: 5,
    fontFamily: 'Open-Sans',
  },
  Venue: {
    width: '95%',
    height: '11%',
    borderWidth: 0,
    borderColor: '#111',
    marginTop: 20,
    alignSelf: 'center',
  },
  venueBlock: {
    width: '90%',
    alignSelf: 'center',
    flex: 1,
    borderWidth: 0,
    borderColor: '#111',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btnVenue: {
    width: '48%',
    justifyContent: 'space-evenly',
    marginTop: 10,
    backgroundColor: '#4169e1',
    borderRadius: 25,
  },
  btnText: {
    alignSelf: 'center',
    color: '#fff',
    fontSize: 18,
  },
  btnSelected: {
    width: '48%',
    justifyContent: 'space-evenly',
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderColor: '#4169e1',
    borderWidth: 1,
  },
  btnSelectedText: {
    color: '#111',
    fontFamily: 'Open-Sans',
  },
  btnCreateMeeting: {
    width: '50%',
    height: '8%',
    marginTop: 25,
    alignSelf: 'center',
    backgroundColor: '#4169e1',
    justifyContent: 'center',
    borderRadius: 25,
    marginBottom: '2%',
  },
  btnCaption: {
    color: '#fff',
    alignSelf: 'center',
    fontSize: 18,
  },
  members: {
    width: '78%',
    flex: 1,
    borderColor: '#111',
    borderWidth: 1,
    alignSelf: 'center',
    marginTop: 30,
  },
  TopView: {
    width: '100%',
    height: '15%',
    borderColor: '#111',
    borderWidth: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  txtMembers: {
    fontSize: 16,
    color: '#111',
    fontFamily: 'Open-Sans',
    alignSelf: 'center',
    marginStart: '2%',
  },
  btnAdd: {
    width: '25%',
    borderColor: '#111',
    borderWidth: 0,
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'row',
  },
  btnCap: {
    fontSize: 18,
    color: '#4169e1',
    fontWeight: '700',
    alignSelf: 'center',
  },
  imgAdd: {
    width: 20,
    height: 20,
    alignSelf: 'center',
  },
  scrollers: {
    flex: 1,
    position: 'absolute',
    zIndex: 900,
  },
  addMemberView: {
    width: '100%',
    height: '50%',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#fff',
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    borderColor: '#C0C0C0',
    borderWidth: 0,
    elevation: 5,
  },
  modalTitle: {
    alignSelf: 'center',
    fontSize: 22,
  },
  contentView: {
    width: '95%',
    flex: 1,
    borderColor: '#111',
    borderWidth: 0,
    alignSelf: 'center',
    marginTop: 25,
  },
  contentTitle: {
    fontSize: 22,
    marginStart: '5%',
    marginTop: '5%',
  },
  txtSearch: {
    width: '95%',
    marginTop: 10,
    elevation: 4,
    alignSelf: 'center',
  },
  head: {
    width: '100%',
    borderColor: '#111',
    borderWidth: 0,
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    marginTop: 15,
  },
  modalClose: {
    position: 'absolute',
    top: '6%',
    right: '5%',
  },
  btnCloseCap: {
    fontSize: 18,
    color: '#111',
  },
  teamContent: {
    width: '95%',
    flex: 1,
    marginTop: 10,
    borderColor: '#111',
    borderWidth: 1,
    alignSelf: 'center',
  },
})
